dist: jammy
language: java

before_install:
  - wget https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
  - sudo dpkg -i jdk-21_linux-x64_bin.deb
  - export JAVA_HOME=/usr/lib/jvm/jdk-21-oracle-x64
  - export PATH=$JAVA_HOME/bin:$PATH
  - cd backend

script:
  - mvn test --batch-mode --fail-at-end

after_script:
  - rm -rf $JAVA_HOME
