export enum PreferenzeAlloggio {
    HOTEL = 'HOTEL',
    BED_AND_BREAKFAST = 'BED_AND_BREAKFAST',
    VILLAGGIO_TURISTICO = 'VILLAGGIO_TURISTICO',
    OSTELLO = 'OSTELLO',
    NESSUNA_PREFERENZA = 'NESSUNA_PREFERENZA',
}
