spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  datasource:
    url: jdbc:mysql://localhost:3306/greentrails
    username: root
    password: admin

server:
  error:
    include-message: always