spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    properties:
      hibernate:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/greentrails
    username: ${DB_USER}
    password: ${DB_PASS}

server:
  error:
    include-message: always
