spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/greentrails
    username: ${DB_USER}
    password: ${DB_PASS}

server:
  error:
    include-message: always