spring:
  jpa:
    properties:
      hibernate:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/greentrails
    username: orfie
    password: Zutuxe98!
server:
  error:
    include-message: always
