name: Backend CI
on:
  push:
    paths:
      - 'backend/**'
#    branches:
#      - dev
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main
      - dev

jobs:
  test:
    name: Esecuzione test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configura ambiente Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Esegui test
        run: mvn test --batch-mode --fail-at-end
      - name: Pubblica test report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

defaults:
  run:
    working-directory: ./backend